name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  migrate-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Show Node/npm
        run: |
          node -v
          npm -v
          npm config get cache

      - name: Install deps (omit optional)
        run: npm install --no-audit --no-fund --omit=optional

      - name: Run DB migrations (via HTTP)
        env:
          MIGRATE_URL: ${{ secrets.MIGRATE_URL }}
          MIGRATE_TOKEN: ${{ secrets.MIGRATE_TOKEN }}
        run: |
          if [ -n "$MIGRATE_URL" ] && [ -n "$MIGRATE_TOKEN" ]; then
            curl -sS -X POST -H "x-admin-token: $MIGRATE_TOKEN" "$MIGRATE_URL" -f
          else
            echo "MIGRATE_URL/MIGRATE_TOKEN not set; skipping HTTP migration."
          fi

      - name: Trigger Vercel Deploy (Deploy Hook)
        if: success()
        run: |
          if [ -n "${{ secrets.VERCEL_DEPLOY_HOOK }}" ]; then
            curl -X POST -H "Content-Type: application/json" "${{ secrets.VERCEL_DEPLOY_HOOK }}" || exit 1
          else
            echo "No VERCEL_DEPLOY_HOOK set; relying on Vercel GitHub auto-deploy.";
          fi
