name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  migrate-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Show Node/npm
        run: |
          node -v
          npm -v
          npm config get cache

      - name: Install deps (omit optional)
        run: npm install --no-audit --no-fund --omit=optional

      - name: Run DB migrations (direct)
        if: ${{ secrets.DB_HOST != '' && secrets.DB_USER != '' && secrets.DB_PASSWORD != '' && secrets.DB_NAME != '' }}
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: node scripts/migrate.cjs

      - name: Run DB migrations (via HTTP)
        if: ${{ secrets.MIGRATE_URL != '' && secrets.MIGRATE_TOKEN != '' }}
        run: |
          curl -sS -X POST -H "x-admin-token: ${{ secrets.MIGRATE_TOKEN }}" "$${{ secrets.MIGRATE_URL }}" -f

      - name: Trigger Vercel Deploy (Deploy Hook)
        if: success()
        run: |
          if [ -n "${{ secrets.VERCEL_DEPLOY_HOOK }}" ]; then
            curl -X POST -H "Content-Type: application/json" "${{ secrets.VERCEL_DEPLOY_HOOK }}" || exit 1
          else
            echo "No VERCEL_DEPLOY_HOOK set; relying on Vercel GitHub auto-deploy.";
          fi
